# Generated by Django 5.2.12 on 2026-03-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wtr_wtrx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='action_network_api_key',
            field=models.CharField(blank=True, help_text='Required for server-side Action Network integrations. Leave blank if using the embed widget approach.', max_length=255, verbose_name='Action Network API key'),
        ),
    ]
