# Generated by Django 5.2.12 on 2026-03-27 01:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wtr_wtrx', '0002_alter_integrationsettings_action_network_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='layout',
            field=models.CharField(choices=[('columns', 'Columns'), ('minimal', 'Minimal')], default='columns', help_text='Columns: multi-column navigation grid. Minimal: single-row bar with logo, copyright, social icons, and inline links.', max_length=20, verbose_name='footer layout'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='minimal_links',
            field=wagtail.fields.StreamField([('internal', 2), ('external', 4), ('anchor', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('anchor', 5)]], {})}, help_text='Flat list of links displayed inline in the minimal footer layout.', verbose_name='minimal footer links'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='collapse_desktop_menu',
            field=models.BooleanField(default=False, help_text='Always show the hamburger menu icon, even on desktop. Navigation links are hidden behind the menu toggle at all screen sizes.', verbose_name='collapse desktop menu'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='cta_anchor',
            field=models.CharField(blank=True, help_text="Anchor link for the CTA button (without the # symbol, e.g. 'donate'). Set this instead of CTA page or CTA URL to link to an anchor on the current page.", max_length=255, verbose_name='CTA anchor'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='show_in_footer',
            field=models.BooleanField(default=True, help_text='Display social media icons in the site footer.', verbose_name='show in footer'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='show_in_header',
            field=models.BooleanField(default=False, help_text='Display social media icons in the site header.', verbose_name='show in header'),
        ),
        migrations.AlterField(
            model_name='brandingseosettings',
            name='dark_logo',
            field=models.ForeignKey(blank=True, help_text='Logo variant for dark or transparent backgrounds (e.g. transparent header).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_wtr_wtrx.customimage', verbose_name='dark logo'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_navigation',
            field=wagtail.fields.StreamField([('column', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Column heading', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 7: ('wagtail.blocks.StructBlock', [[('text', 1), ('anchor', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('internal', 3), ('external', 5), ('anchor', 7)]], {'label': 'Links'}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 8)]], {})}, help_text='Footer link columns. Each column has a heading and a list of links.', verbose_name='footer navigation'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='primary_navigation',
            field=wagtail.fields.StreamField([('internal', 2), ('external', 4), ('anchor', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('anchor', 5)]], {})}, help_text='Links shown in the main navigation bar.', verbose_name='primary navigation'),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='social_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon')], 'label': 'Platform'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})}, verbose_name='social links'),
        ),
    ]
