# Generated by Django 5.2.12 on 2026-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wtr_home', '0005_alter_homepage_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='use_transparent_header',
            field=models.BooleanField(default=False, help_text='Make the header transparent so the hero image extends behind it. Automatically uses the dark logo variant when enabled.', verbose_name='transparent header'),
        ),
    ]
