# Generated by Django 5.2.15 on 2026-07-08 15:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0004_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='primary_navigation',
            field=wagtail.fields.StreamField([('internal', 2), ('external', 4), ('anchor', 6), ('submenu', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('anchor', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Menu label'}), 8: ('wagtail.blocks.StreamBlock', [[('internal', 2), ('external', 4), ('anchor', 6)]], {'label': 'Dropdown links'}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('links', 8)]], {})}, help_text='Links shown in the main navigation bar.', verbose_name='primary navigation'),
        ),
    ]
