# Generated by Django 5.2.16 on 2026-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0005_alter_navigationsettings_primary_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='actionkit_page',
            field=models.CharField(blank=True, help_text='The ActionKit page short name this form submits to. Only used when the signup platform (Settings → Integrations) is set to ActionKit. Leave blank to disable ActionKit forwarding for this form.', max_length=255, verbose_name='ActionKit page name'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='actionkit_api_password',
            field=models.CharField(blank=True, help_text='The ActionKit REST API password. In production, prefer the WTRX_ACTIONKIT_API_PASSWORD environment variable, which overrides this value so the secret is not stored in the database.', max_length=255, verbose_name='ActionKit API password'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='actionkit_api_username',
            field=models.CharField(blank=True, help_text='The ActionKit REST API username used for HTTP Basic auth.', max_length=255, verbose_name='ActionKit API username'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='actionkit_hostname',
            field=models.CharField(blank=True, help_text="Your ActionKit instance hostname, e.g. 'myorg.actionkit.com' (no scheme or trailing slash needed).", max_length=255, verbose_name='ActionKit hostname'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='signup_platform',
            field=models.CharField(choices=[('wagtail_forms', 'Wagtail Forms (built-in)'), ('action_network', 'Action Network'), ('actionkit', 'ActionKit'), ('none', 'None')], default='wagtail_forms', max_length=50, verbose_name='signup platform'),
        ),
    ]
