# Generated by Django 5.2.16 on 2026-07-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wtrx', '0006_formpage_actionkit_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_index_page', models.ForeignKey(blank=True, help_text="The page that lists your blog posts. When set, a 'Blog' shortcut appears in the admin sidebar linking to it. Leave blank to hide the shortcut.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='blog index page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Admin menu',
            },
        ),
    ]
