# Generated by Django 5.2.16 on 2026-08-09 19:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0010_remove_integrationsettings_action_network_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='navigation_overrides',
            field=wagtail.fields.StreamField([('override', 17)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'This page and every page beneath it will use this navigation instead of the default. If a page falls under more than one override, the override with the most specific (closest) root page wins.', 'label': 'Root page'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 7: ('wagtail.blocks.StructBlock', [[('text', 1), ('anchor', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Menu label'}), 9: ('wagtail.blocks.StreamBlock', [[('internal', 3), ('external', 5), ('anchor', 7)]], {'label': 'Dropdown links'}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('links', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('internal', 3), ('external', 5), ('anchor', 7), ('submenu', 10)]], {'blank': True, 'help_text': 'Links shown in the main navigation bar for this section.', 'label': 'primary navigation'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'CTA button text', 'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal link for the CTA button. Set either this, CTA URL, or CTA anchor, not more than one.', 'label': 'CTA page', 'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link for the CTA button. Set either this, CTA page, or CTA anchor, not more than one.', 'label': 'CTA URL', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor link for the CTA button (without the # symbol, e.g. 'donate'). Set this instead of CTA page or CTA URL to link to an anchor on the current page.", 'label': 'CTA anchor', 'required': False}), 16: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Always show the hamburger menu icon, even on desktop, for this section.', 'label': 'collapse desktop menu', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('root_page', 0), ('primary_navigation', 11), ('cta_text', 12), ('cta_page', 13), ('cta_url', 14), ('cta_anchor', 15), ('collapse_desktop_menu', 16)]], {})}, help_text='Alternate navigations for specific sections of the site. Each override applies to a chosen root page and every page beneath it; pages outside any override use the default navigation above.', verbose_name='navigation overrides'),
        ),
    ]
