# Generated by Django 5.2.16 on 2026-08-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0005_alter_media_options'),
        ('wtrx', '0019_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text="Optional. When set, this video autoplays (muted, looping) as the hero's full-bleed background instead of the hero image, with a pause/play button in the corner. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.", limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text="Optional. When set, this video autoplays (muted, looping) as the hero's full-bleed background instead of the hero image, with a pause/play button in the corner. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.", limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text="Optional. When set, this video autoplays (muted, looping) as the hero's full-bleed background instead of the hero image, with a pause/play button in the corner. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.", limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
    ]
