# Generated by Django 5.2.16 on 2026-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0025_blogcategory_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(blank=True, help_text="Byline for a guest writer or imported post who doesn't have a site account. Ignored if Author (above) is set.", max_length=255, verbose_name='author name'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_title',
            field=models.CharField(blank=True, help_text='Optional role/affiliation shown next to Author name, e.g. "Senior Campaigner at Oil Change International".', max_length=255, verbose_name='author title'),
        ),
    ]
