# Generated by Django 5.2.17 on 2026-08-24 22:53

import django.db.models.deletion
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0005_alter_media_options'),
        ('wtrx', '0028_merge_blog_and_press_release_into_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_banner_color',
            field=models.CharField(choices=[('navy', 'Navy'), ('red', 'Red'), ('dark-grey', 'Dark grey'), ('blue-gradient', '350 Blue'), ('light-grey', 'Light grey')], default='navy', help_text='Background color for the compact hero banner. Only affects pages whose hero renders as a banner (i.e. every page except the homepage).', max_length=20, verbose_name='hero banner color'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_copy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional subtext displayed below the headline.', verbose_name='hero copy'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_cta',
            field=wagtail.fields.StreamField([('signup', 17), ('donate', 23), ('announcement', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Signup section heading, shown above the ActionKit form.', 'label': 'Heading', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ai'], 'help_text': 'Optional supporting text below the heading.', 'label': 'Description', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption overlaid on the image, e.g. a photo credit.', 'label': 'Image caption', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "The ActionKit page's short name (e.g. 'join'). Its signup form is fetched from ActionKit and rendered automatically — whatever fields that page is configured with will appear, with no further setup needed here.", 'label': 'ActionKit Page Shortname'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional. Adds an id attribute for deep-linking (e.g. 'contact' → #contact).", 'label': 'Anchor ID', 'required': False}), 6: ('wtrx.blocks.TextBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overrides the image title for screen readers. Leave blank to use the image title.', 'label': 'Alt text', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the image.', 'label': 'Caption', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('alt_text', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link. Set either this or Link URL, not both.', 'label': 'Link page', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link. Set either this or Link page, not both.', 'label': 'Link URL', 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], 'label': 'Style'}), 15: ('wagtail.blocks.StructBlock', [[('text', 11), ('link_page', 12), ('link_url', 13), ('style', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('text', 6), ('image', 10), ('button', 15)]], {'help_text': "Optional. When set, a successful signup shows this message in place of the form instead of redirecting to ActionKit's own thank-you page. ActionKit's normal submission is a full-page POST directly to ActionKit, so this works by forwarding the signup through our own server (the same integrations.actionkit.submit_action REST call FormPage signups already use) instead — which does not go through ActionKit's own recaptcha check, the same trade-off that forwarding already accepts elsewhere.", 'label': 'Success message', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('image', 2), ('image_caption', 3), ('short_form_id', 4), ('anchor_id', 5), ('success_message', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Donation section heading.', 'label': 'Heading', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Donate', 'help_text': 'Leave blank to use the site default button label.', 'label': 'Button text', 'required': False}), 20: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'min_value': Decimal('0.01')}), 21: ('wagtail.blocks.ListBlock', (20,), {'help_text': 'Optional list of suggested donation amounts. Leave empty to use the site-wide defaults.', 'label': 'Override amounts', 'required': False}), 22: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional override for the donation URL. Overrides the site-wide donation base URL from IntegrationSettings.', 'label': 'Override URL', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading', 18), ('description', 1), ('button_text', 19), ('override_amounts', 21), ('override_url', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Text'}), 25: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal link. Set either this or Link URL, not both.', 'label': 'Link page', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('text', 24), ('link_page', 25), ('link_url', 13)]], {})}, help_text='Optional signup bar, donate block, or announcement bar shown below the hero copy. At most one.', verbose_name='hero call to action'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Optional. Overrides the page title as the displayed heading. Leave blank to use the page title.', max_length=255, verbose_name='hero headline'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional hero background or feature image. Also used as the video poster if no thumbnail is set on the video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='hero image'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_layout',
            field=models.CharField(choices=[('centered', 'Centered'), ('left', 'Left-aligned')], default='centered', help_text="Centered text over the image, or left-aligned and anchored toward the bottom. Only affects the homepage's full-viewport hero — every other page's hero renders as a compact banner with a fixed layout.", max_length=20, verbose_name='hero layout'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text="Optional. When set, this video autoplays (muted, looping) as the hero's full-bleed background instead of the hero image, with a pause/play button in the corner. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.", limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
    ]
