# Generated by Django 5.2.17 on 2026-08-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0030_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='related_intro',
            field=models.TextField(blank=True, help_text='Supporting copy under the "Related …" heading at the bottom of each post under this page. Falls back to this page\'s header copy when blank.', verbose_name='related posts intro'),
        ),
    ]
