# Generated by Django 5.2.17 on 2026-08-25 20:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0034_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='regional_label',
            field=models.CharField(blank=True, help_text='Region name shown as a badge beside the logo across the whole site, e.g. "Canada". Leave blank for no badge. Sections with their own navigation override set this on the override instead.', max_length=50, verbose_name='regional label'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='navigation_overrides',
            field=wagtail.fields.StreamField([('override', 18)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'This page and every page beneath it will use this navigation instead of the default. If a page falls under more than one override, the override with the most specific (closest) root page wins.', 'label': 'Root page'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Region name shown as a badge beside the logo for this section, e.g. "Canada". Leave blank for no badge.', 'label': 'Regional label', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('page', 3)]], {}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 6: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 8: ('wagtail.blocks.StructBlock', [[('text', 2), ('anchor', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Menu label'}), 10: ('wagtail.blocks.StreamBlock', [[('internal', 4), ('external', 6), ('anchor', 8)]], {'label': 'Dropdown links'}), 11: ('wagtail.blocks.StructBlock', [[('text', 9), ('links', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('internal', 4), ('external', 6), ('anchor', 8), ('submenu', 11)]], {'blank': True, 'help_text': 'Links shown in the main navigation bar for this section.', 'label': 'Primary navigation'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'CTA button text', 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal link for the CTA button. Set either this, CTA URL, or CTA anchor, not more than one.', 'label': 'CTA page', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link for the CTA button. Set either this, CTA page, or CTA anchor, not more than one.', 'label': 'CTA URL', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor link for the CTA button (without the # symbol, e.g. 'donate'). Set this instead of CTA page or CTA URL to link to an anchor on the current page.", 'label': 'CTA anchor', 'required': False}), 17: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Always show the hamburger menu icon, even on desktop, for this section.', 'label': 'Collapse desktop menu', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('root_page', 0), ('regional_label', 1), ('primary_navigation', 12), ('cta_text', 13), ('cta_page', 14), ('cta_url', 15), ('cta_anchor', 16), ('collapse_desktop_menu', 17)]], {})}, help_text='Alternate navigations for specific sections of the site. Each override applies to a chosen root page and every page beneath it; pages outside any override use the default navigation above.', verbose_name='navigation overrides'),
        ),
    ]
