# Generated by Django 5.2.16 on 2026-08-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0035_navigationsettings_regional_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Optional. Set if this page's content is duplicated elsewhere and search engines should treat another URL as the primary version. Defaults to this page's own URL.", verbose_name='canonical URL'),
        ),
    ]
