# Generated by Django 5.2.16 on 2026-08-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0036_blogs_canonical_url_contentpage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingseosettings',
            name='twitter_site',
            field=models.CharField(blank=True, help_text="The @username of the site's Twitter/X account, e.g. @350. Used in the twitter:site meta tag on every page.", max_length=20, verbose_name='Twitter/X account'),
        ),
    ]
