# Generated by Django 5.2.16 on 2026-08-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wtrx', '0037_brandingseosettings_twitter_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmenusettings',
            name='press_releases_index_page',
            field=models.ForeignKey(blank=True, help_text="The page that lists your press releases. When set, a 'Press releases' shortcut appears in the admin sidebar linking to it. Leave blank to hide the shortcut.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='press releases index page'),
        ),
    ]
