# Generated by Django 5.2.16 on 2026-08-27 21:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0041_alter_blogs_hero_cta_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_overrides',
            field=wagtail.fields.StreamField([('override', 16)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'This page and every page beneath it will use this footer instead of the default. If a page falls under more than one override, the override with the most specific (closest) root page wins.', 'label': 'Root page'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Region name shown as a badge beside the logo for this section, e.g. "Canada". Leave blank for no badge.', 'label': 'Regional label', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('minimal', 'Minimal')], 'help_text': 'Leave blank to use the columns layout.', 'label': 'Footer layout', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Column heading', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 8: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 10: ('wagtail.blocks.StructBlock', [[('text', 4), ('anchor', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('internal', 6), ('external', 8), ('anchor', 10)]], {'label': 'Links'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 3), ('links', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('column', 12)]], {'blank': True, 'help_text': 'Footer link columns for this section. Each column has a heading and a list of links.', 'label': 'Footer navigation'}), 14: ('wagtail.blocks.StreamBlock', [[('internal', 6), ('external', 8), ('anchor', 10)]], {'blank': True, 'help_text': 'Flat list of links displayed inline in the minimal footer layout for this section.', 'label': 'Minimal footer links'}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional. Overrides the default "© {year} {site name}" copyright line for this section.', 'label': 'Copyright text', 'max_length': 255, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('root_page', 0), ('regional_label', 1), ('layout', 2), ('footer_navigation', 13), ('minimal_links', 14), ('copyright_text', 15)]], {})}, help_text='Alternate footers for specific sections of the site. Each override applies to a chosen root page and every page beneath it; pages outside any override use the default footer above.', verbose_name='footer overrides'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='regional_label',
            field=models.CharField(blank=True, help_text='Region name shown as a badge beside the logo across the whole site, e.g. "Canada". Leave blank for no badge. Sections with their own footer override set this on the override instead.', max_length=50, verbose_name='regional label'),
        ),
    ]
