# Generated by Django 5.2.16 on 2026-08-27 21:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0042_footersettings_footer_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='regional_sites',
            field=wagtail.fields.StreamField([('site', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Canada".', 'label': 'Region name'}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to that region's site.", 'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1)]], {})}, help_text='Links to other regional 350.org sites, shown in an "Around the World" dropdown beside the footer logo on every page — the same list regardless of any footer override, since it isn\'t region-specific content itself.', verbose_name='regional sites'),
        ),
    ]
