# Folds the separate heading (+ subheading) fields of ImageTextBlock,
# FeaturePanelBlock, CalloutBlock and CardCarouselBlock into each block's
# single `content` richtext field, without losing any existing content.
#
# Before this, each block had its heading typed into its own CharBlock,
# rendered as a bare <h2>/<h3> beside a separate richtext body field. They
# are now one richtext field per block — the editor types the heading
# inline as an H2 (and, for CalloutBlock, an optional H3 subheading) —
# matching the convention SectionBlock's own content list already uses.
# See each block's docstring in wtrx/blocks/__init__.py.
#
# This only rewrites the JSON *values*; the schema-level AlterField
# bookkeeping migration (generated by makemigrations, dependent on this one)
# reflects the new block_lookup shape but changes nothing at the DB level —
# StreamField is one opaque column regardless of its block definition.
#
# Same technique as 0040_unify_block_background_values: walk the raw
# StreamField JSON (not `to_python()` — the old block definition's shape is
# gone from the code by the time this runs) for both live objects and their
# revisions, since reverting to an unmigrated revision would otherwise
# silently bring the old heading/text keys back.
import json

from django.db import migrations
from django.utils.html import escape

CHAR_FIELDS_TO_DROP = {
    "image_text": ("heading",),
    "feature_panel": ("heading",),
    "callout": ("heading", "subheading"),
    "card_carousel": ("heading",),
}

# The pre-migration richtext body field's name on each block -- ImageTextBlock
# and FeaturePanelBlock called theirs "text"; CalloutBlock and
# CardCarouselBlock already called theirs "content" (which the merged field
# reuses). Popped rather than merely read, so no stale "text" key is left
# behind on the two blocks being renamed.
TEXT_SOURCE_FIELD = {
    "image_text": "text",
    "feature_panel": "text",
    "callout": "content",
    "card_carousel": "content",
}


def _combine(block_type, value):
    """Fold value's dropped CharBlock field(s) into its `content` richtext field, in place."""
    heading = escape(value.pop("heading", "") or "")
    existing_content = value.pop(TEXT_SOURCE_FIELD[block_type], "") or ""

    if block_type == "callout":
        subheading = escape(value.pop("subheading", "") or "")
        parts = []
        if heading:
            parts.append(f"<h2>{heading}</h2>")
        if subheading:
            parts.append(f"<h3>{subheading}</h3>")
        parts.append(existing_content)
        value["content"] = "".join(parts)
    else:
        # image_text/feature_panel/card_carousel all required a heading, so
        # every existing instance has one -- content always gets an <h2>.
        value["content"] = f"<h2>{heading}</h2>{existing_content}"


def _rewrite(node):
    """
    Walk parsed StreamField JSON, condensing heading(+subheading) fields into
    `content` in place. Returns True if anything changed.

    Blocks nest arbitrarily (a section holds content, a card grid holds
    cards), so this recurses through every list and dict rather than
    assuming a fixed shape.
    """
    changed = False
    if isinstance(node, list):
        for item in node:
            changed |= _rewrite(item)
    elif isinstance(node, dict):
        block_type = node.get("type")
        value = node.get("value")
        if (
            block_type in CHAR_FIELDS_TO_DROP
            and isinstance(value, dict)
            # "heading" is always present in raw_data pre-migration (Wagtail
            # serializes every declared child block, blank or not) and always
            # absent post-migration -- doubles as the idempotency guard.
            and "heading" in value
        ):
            _combine(block_type, value)
            changed = True
        for child in node.values():
            if isinstance(child, (list, dict)):
                changed |= _rewrite(child)
    return changed


def _stream_field_names(model):
    from wagtail.fields import StreamField

    return [f.name for f in model._meta.get_fields() if isinstance(f, StreamField)]


def forwards(apps, schema_editor):
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type_ids = []
    # apps.get_app_config("wtrx").get_models() comes back empty against the
    # migration state's AppConfigStub; get_models() on the state itself does not.
    for model in [m for m in apps.get_models() if m._meta.app_label == "wtrx"]:
        field_names = _stream_field_names(model)
        if not field_names:
            continue

        for obj in model.objects.all().iterator():
            dirty = False
            for name in field_names:
                # list() is load-bearing: StreamValue.raw_data is a lazy
                # RawDataView, not a list, so _rewrite would not recognise it
                # as a sequence and would walk nothing at all.
                raw = list(getattr(obj, name).raw_data)
                if _rewrite(raw):
                    setattr(obj, name, json.dumps(raw))
                    dirty = True
            if dirty:
                obj.save(update_fields=field_names)

        # Revisions hold their own copy of the same JSON, and reverting to
        # one republishes it -- so an unmigrated revision would quietly
        # bring the old heading/text keys back.
        ct = ContentType.objects.filter(
            app_label="wtrx", model=model._meta.model_name
        ).first()
        if ct is not None:
            content_type_ids.append((ct.pk, field_names))

    for ct_id, field_names in content_type_ids:
        for revision in Revision.objects.filter(content_type_id=ct_id).iterator():
            content = revision.content
            if not isinstance(content, dict):
                continue
            dirty = False
            for name in field_names:
                stored = content.get(name)
                if not isinstance(stored, str) or not stored.strip():
                    continue
                try:
                    parsed = json.loads(stored)
                except ValueError:
                    continue
                if _rewrite(parsed):
                    content[name] = json.dumps(parsed)
                    dirty = True
            if dirty:
                revision.content = content
                revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("wtrx", "0044_alter_contentpage_body_alter_homepage_body_and_more"),
    ]

    operations = [
        # Not cleanly reversible: splitting one freeform richtext field back
        # into a heading CharBlock + separate text field is ambiguous once an
        # editor has actually edited the merged content (which H2, if any, was
        # "the heading"?). RunPython.noop lets `migrate` backwards proceed
        # without attempting a lossy, guessed-at split.
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
