# Generated by Django 5.2.16 on 2026-08-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0043_alter_contentpage_body_alter_homepage_body_and_more'),
        ('wtrx', '0045_footersettings_newsletter_success_message_and_more'),
    ]

    operations = [
    ]
