# Generated by Django 5.2.17 on 2026-08-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0046_merge_20260828_1728'),
        ('wtrx', '0052_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
    ]
