# Generated by Django 5.2.16 on 2026-08-31 15:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0053_merge_20260828_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='regional_sites',
            field=wagtail.fields.StreamField([('site', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Canada".', 'label': 'Region name'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional. Shown as a subheading below the region name — for a linked site that isn\'t a regional site itself and needs a line of context (e.g. "350 Action", "350 Global"). Entries with a description render in their own two-column row below the plain region links, since the extra text needs more room.', 'label': 'Description', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to that region's site.", 'label': 'URL'}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('description', 1), ('url', 2)]], {})}, help_text='Links to other regional 350.org sites, shown in an "Around the World" dropdown beside the footer logo on every page — the same list regardless of any footer override, since it isn\'t region-specific content itself.', verbose_name='regional sites'),
        ),
    ]
