# Generated by Django 5.2.16 on 2026-08-31 18:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0054_alter_footersettings_regional_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsettings',
            name='social_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('whatsapp', 'WhatsApp')], 'label': 'Platform'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})}, verbose_name='social links'),
        ),
    ]
