# Generated by Django 5.2.16 on 2026-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0058_default_content_feedback_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide_from_blogroll',
            field=models.BooleanField(default=False, help_text='Exclude this post from the Blogs page listing and from any "latest posts" cards elsewhere on the site (e.g. Page Cards on the home page). The post is still directly accessible and still appears in search.', verbose_name='hide from blogroll'),
        ),
    ]
