# Generated by Django 5.2.17 on 2026-09-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0060_alter_blogs_hero_cta_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='description',
            field=models.CharField(default='', help_text='Used as alt text for screen readers. Describe what the image shows.', max_length=255, verbose_name='description'),
        ),
    ]
