# Generated by Django 5.2.17 on 2026-09-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0068_migrate_admin_menu_shortcuts_and_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmenusettings',
            name='blog_index_page',
        ),
        migrations.RemoveField(
            model_name='adminmenusettings',
            name='press_releases_index_page',
        ),
        migrations.RemoveField(
            model_name='brandingseosettings',
            name='twitter_site',
        ),
    ]
