# Generated by Django 5.2.16 on 2026-09-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0073_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='default_card_image',
            field=models.ForeignKey(blank=True, help_text="Shown for any post under this page that has no image of its own (no header image, and none found in its body content) — both as its own header and wherever it's shown as a card. Useful for a Press Releases page, where a statement often has no photo. Leave blank for no fallback.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='default card image'),
        ),
    ]
