# Generated by Django 5.2.16 on 2026-09-19 16:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wtrx', '0074_blogs_default_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_links', wagtail.fields.StreamField([('internal', 2), ('external', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 3)]], {})}, help_text='Buttons shown on the 404 page below the search box, e.g. links to your About, Blog, Press Releases, Take Action and Contact pages. Leave empty to hide this row entirely.', verbose_name='quick links')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Photo shown beside the headline on the 404 page. Leave blank for a plain color panel with no image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='hero image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': '404 page',
            },
        ),
    ]
