# Generated by Django 5.2.16 on 2026-09-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0076_alter_footersettings_footer_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='default_hero_image',
            field=models.ForeignKey(blank=True, help_text='Shown as the header image for any post under this page that has no image of its own, instead of Default card image (above) — for when the two should differ, e.g. a generic banner graphic at the top of the post versus a smaller icon on its card. Falls back to Default card image when left blank. Leave both blank for no fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='default hero image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='default_card_image',
            field=models.ForeignKey(blank=True, help_text='Shown for any post under this page that has no image of its own (no header image, and none found in its body content) wherever it\'s shown as a card — the listing below, "Related …" panels, and Page Cards blocks. Also used as that post\'s own header image when Default hero image (below) is left blank. Useful for a Press Releases page, where a statement often has no photo. Leave blank for no fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='default card image'),
        ),
    ]
