# Generated by Django 5.2.17 on 2026-09-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0080_alter_blogs_hero_cta_alter_contentpage_body_and_more'),
        ('wtrx', '0080_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
    ]
