# Generated by Django 5.2.16 on 2026-09-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0082_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hero_copy',
        ),
    ]
