# Generated by Django 5.2.17 on 2026-09-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0090_hero_headline_to_paragraphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='use_transparent_header',
        ),
        migrations.AlterField(
            model_name='brandingseosettings',
            name='dark_logo',
            field=models.ForeignKey(blank=True, help_text='Logo variant for dark backgrounds, used in the footer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtrx.customimage', verbose_name='dark logo'),
        ),
    ]
