# Generated by Django 5.2.17 on 2026-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0092_spacer_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Media index', 'verbose_name_plural': 'Media indexes'},
        ),
    ]
