# Generated by Django 5.2.16 on 2026-10-06 13:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0095_signup_post_signup_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='show_social_in_footer',
            field=models.BooleanField(default=True, help_text='Display social media icons in the site footer.', verbose_name='show in footer'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_social_in_header',
            field=models.BooleanField(default=False, help_text='Display social media icons in the site header.', verbose_name='show in header'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('whatsapp', 'WhatsApp')], 'label': 'Platform'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})}, help_text='Sections with their own footer override can set their own social links on the override; an override with none uses these.', verbose_name='social links'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_overrides',
            field=wagtail.fields.StreamField([('override', 23)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'This page and every page beneath it will use this footer instead of the default. If a page falls under more than one override, the override with the most specific (closest) root page wins.', 'label': 'Root page'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Region name shown as a badge beside the logo for this section, e.g. "Canada". Leave blank for no badge.', 'label': 'Regional label', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('minimal', 'Minimal')], 'help_text': 'Leave blank to use the columns layout.', 'label': 'Footer layout', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Column heading', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Link text'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page'}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 8: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "Anchor ID without the # symbol, e.g. 'about'.", 'label': 'Anchor'}), 10: ('wagtail.blocks.StructBlock', [[('text', 4), ('anchor', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('internal', 6), ('external', 8), ('anchor', 10)]], {'label': 'Links'}), 12: ('wagtail.blocks.StructBlock', [[('heading', 3), ('links', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('column', 12)]], {'blank': True, 'help_text': 'Footer link columns for this section. Each column has a heading and a list of links.', 'label': 'Footer navigation'}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': "Where this link goes for visitors outside the EU/UK, or when Usercentrics isn't configured. EU/UK visitors get the Usercentrics preferences panel instead of this URL.", 'label': 'Cookie policy URL'}), 15: ('wagtail.blocks.StructBlock', [[('text', 4), ('policy_url', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('internal', 6), ('external', 8), ('anchor', 10), ('cookie_settings', 15)]], {'blank': True, 'help_text': 'Flat list of links displayed inline in the minimal footer layout for this section.', 'label': 'Minimal footer links'}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional. Overrides the default "© {year} {site name}" copyright line for this section.', 'label': 'Copyright text', 'max_length': 255, 'required': False}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('whatsapp', 'WhatsApp')], 'label': 'Platform'}), 19: ('wagtail.blocks.StructBlock', [[('platform', 18), ('url', 7)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('link', 19)]], {'help_text': "Social media links for this section, shown in its footer (and its header, when social icons are switched on there). Leave empty to use the site default's social links (unlike the other fields on this override, which show nothing rather than fall back).", 'label': 'Social links', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': "The ActionKit page's short name (e.g. 'newsletter-canada') powering this section's footer signup box. Leave blank to show no signup box for this section, even if the site default has one set.", 'label': 'Newsletter signup — ActionKit page shortname', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': "Shown in place of the form after a successful signup for this section. Falls back to the site default's message when left blank (unlike the other fields on this override, which show nothing rather than fall back).", 'label': 'Newsletter signup — success message', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('root_page', 0), ('regional_label', 1), ('layout', 2), ('footer_navigation', 13), ('minimal_links', 16), ('copyright_text', 17), ('social_links', 20), ('newsletter_actionkit_shortname', 21), ('newsletter_success_message', 22)]], {})}, help_text='Alternate footers for specific sections of the site. Each override applies to a chosen root page and every page beneath it; pages outside any override use the default footer above.', verbose_name='footer overrides'),
        ),
    ]
