# Generated by Django 5.2.16 on 2026-10-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0097_move_social_settings_to_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialSettings',
        ),
    ]
