# Generated by Django 5.2.16 on 2026-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtrx', '0098_delete_socialsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='related_heading',
            field=models.CharField(blank=True, help_text='Heading of the "Related …" section at the bottom of each post under this page. Leave blank to build it from this page\'s title ("Related press releases"), which only reads correctly in English — fill it in on a page in any other language.', max_length=255, verbose_name='related posts heading'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='related_link_text',
            field=models.CharField(blank=True, help_text='Text of the button under that section, which links back to this page. Leave blank to build it from this page\'s title ("Read more press releases"), which only reads correctly in English — fill it in on a page in any other language.', max_length=255, verbose_name='related posts button text'),
        ),
    ]
